### ISSUE TITLE
`facilitator`: do something with packet decryption error

### ISSUE THREAD

**Issue by tgeoghegan** [divviup/prio-server#1033]
Currently, if we fail to decrypt a packet, we just drop the error, because we will iterate over several available packet decryption keys looking for one that works. We should do _something_ with that error:

- record a metric on failed decryptions
- log something at WARN
- hold on to the last decryption error or all of them so that we can log something interesting if no available packet decryption key works

**Comment by BranLwyd** [comment]
IMO, since in the presence of key rotation we'll regularly have multiple decryption keys to try, it makes sense to treat failure to decrypt with a *single* key as a  "normal" non-erroneous thing that can happen. OTOH, failure to decrypt with *all available* keys is an error that should be reported, and it makes sense to report the specific error (or all of them, if we don't mind holding the errors in memory while we try the remaining keys).
