### ISSUE TITLE
workflow-manager: Credentials for S3 requests are not cached

### ISSUE THREAD

**Issue by divergentdave** [divviup/prio-server#1832]
I noticed that [`S3Bucket.service()`](https://github.com/divviup/prio-server/blob/d0b67022ebfa26affa14edee73f1efe56afd1521/workflow-manager/storage/storage.go#L143-L154) does not set `b.s3Service` after it creates a new SDK object. As a result, we are [creating a new `credentials.Credentials`](https://github.com/divviup/prio-server/blob/d0b67022ebfa26affa14edee73f1efe56afd1521/workflow-manager/aws/aws.go#L16-L43) for each request. Normally, this object would cache credentials until they expire, but since we're creating a fresh one for each S3 request, we have to hit STS to exchange a Kubernetes token for an IAM token each time. This is likely contributing to the STS errors we've seen in prod-intl.

**Comment by divergentdave** [comment]
Ah, upon a closer look, I see `webIDP()` is only used when on GKE and reading from S3. In that case, this wouldn't be related to prod-intl. Moreover, it seems like we don't ever set any of the `-identity` command line flags in practice in our deployments.

Nevertheless, we do call `s3.New()` on each S3 operation, though with an `aws.Config` that has no `Credentials` object set. I presume that the default credentials used in EKS are similarly affected by us not reusing `credentials.Credentials` between requests. (and result in errors regarding the STS endpoint)

**Comment by tgeoghegan** [comment]
It's worth noting that we'll only ever get limited benefits from caching creds in `workflow-manager` because a new process is started every ten minutes. It'd be nice if we could cache the creds across runs of the cronjob. All that said, we will make quite a few S3 API requests in a single run of `workflow-manager`, so better caching would probably cut out a lot of API traffic to sts and iam.
