### ISSUE TITLE
Upgrade EKS clusters to Kubernetes 1.22

### ISSUE THREAD

**Issue by divergentdave** [divviup/prio-server#2249]
We just received deprecation notices from AWS stating that Kubernetes 1.21 will no longer be supported as of 2/15/23. We should upgrade our clusters before then, and fix any compatibility issues found along the way.

**Comment by tgeoghegan** [comment]
I can take care of this as part of my oncall shift next week (December 5-9).

<details><summary>This is the email from Amazon, which contains some useful links to documentation</summary>

>Hello,
>
>Amazon EKS has deprecated Kubernetes version 1.21 and this version will no longer be supported on February 15, 2023. Starting that day, you will no longer be able to create new 1.21 clusters and all EKS clusters running Kubernetes version 1.21 will be updated to the latest available platform version of Kubernetes version 1.22.
>
>You are receiving this message because you currently have one or more EKS clusters running with Kubernetes version 1.21. The following is a list of your affected resource(s):
>
><cluster ARN>
>
>We recommend that you update your 1.21 clusters to Kubernetes version 1.22 or higher. You can minimize the frequency at which you need to perform version upgrades by updating your cluster up to the latest supported Kubernetes version, which is version 1.24.
>
>To learn more on Kubernetes version support, see the Amazon EKS service documentation [1].
For instructions on how to update your cluster(s), see the Amazon EKS service documentation [2].
>
>If you have any questions or concerns, please reach out to AWS Support [3].
>
>[1] https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html
>[2] https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html
>[3] https://aws.amazon.com/support
</details>

**Comment by tgeoghegan** [comment]
Hit an interesting snag here after updating the Kubernetes cluster and plugins in our US staging PHA deployment: Kubernetes 1.22 deprecated the `apiextensions.k8s.io/v1beta1` API and promoted it to `apiextensions.k8s.io/v1` ([release notes](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/)). We happen to use an `externalmetrics.metrics.aws` CRD to run the Cloudwatch mertics adapter (which incidentally is now unmaintained; #2280) which we need for pod autoscaling. The cluster upgrade automatically migrated the CRD in the cluster to the new API version (that's good), but now I think Terraform is confused, because it can't figure out where this one [`kubernetes_manifest` resource](https://github.com/divviup/prio-server/blob/846a16412fbcebbfaecb0cc16db53cb476ba9bad/terraform/modules/custom_metrics/custom_metrics.tf#L307) went.

I think the way forward here is to `terraform state rm` the `kubernetes_manifest` resource from state, then `terraform import` the CRD in, which should reconcile things.

**Comment by tgeoghegan** [comment]
We'll need to take #2281 to account for a change to the `CustomResourceDefinition` Kubernetes API. Once we have that merged, we have to do a bit of state surgery.

Here's what we need to do in each EKS cluster (`stg-us-pha`, `staging-intl`, `prod-intl`). We use several targets from `prio-server/terraform/Makefile` here. We omit the environment variables and setup to get appropriate cloud credentials for each env to keep this implementation plan brief.

## Make a working copy of remote `.tfstate`

- set up cloud authentication (either obtaining MFAed credentials or setting appropriate `AWS_PROFILE` env var)
- set up the remote backend: `ENV=<env> make plan`
- `terraform state pull > /local/state/copy/path`

## Configure local backend

Apply this patch to `prio-server`:

```
diff --git a/terraform/Makefile b/terraform/Makefile
index 0f61719d..2510eaed 100644
--- a/terraform/Makefile
+++ b/terraform/Makefile
@@ -41,8 +41,8 @@ prep: ## Prepare a new workspace (environment) if needed, configure the tfstate
 		-input=false \
 		-force-copy \
 		-upgrade \
-		-backend=true \
-		-backend-config="bucket=$(STATE_BUCKET)"
+		-backend=true #\
+		#-backend-config="bucket=$(STATE_BUCKET)"
 
 .PHONY: validate
 validate: prep ## Show what terraform believes about the validity of the defined resources
diff --git a/terraform/main.tf b/terraform/main.tf
index d05bc7ed..ed2db2e6 100644
--- a/terraform/main.tf
+++ b/terraform/main.tf
@@ -352,7 +352,9 @@ variable "enable_heap_profiles" {
 }
 
 terraform {
-  backend "gcs" {}
+  backend "local" {
+    path = "/local/state/copy/path"
+  }
 
   required_version = ">= 1.3.1"
 ```

`make prep` to initialize local backend

## Delete the old `kubernetes_manifest` resource from `.tfstate` and import the currently existing one

The Kubernetes cluster upgrade will have automatically migrated the CRD in the cluster to the new layout, so we don't want to mess with anything in Kubernetes. We merely want to fix Terraform's state.

- delete the old CRD resource from state: `terraform state rm module.custom_metrics.kubernetes_manifest.external_metrics_crd[0]`
- import the one in the cluster: `terraform import -var-file variables/<environment>.tfvars module.custom_metrics.kubernetes_manifest.external_metrics_crd[0] "apiVersion=apiextensions.k8s.io/v1,kind=CustomResourceDefinition,name=externalmetrics.metrics.aws"`

See [`kubernetes_manifest` Terraform resource docs](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#importing-existing-kubernetes-resources-as-kubernetes_manifest) for details on the syntax for importing a `kubernetes_manifest`.

## Verify and push local state to remote

- `ENV=<env> make plan`. The plan should only be trying to modify the CRD or do other expected things like update the `cluster-autoscaler`.
- remove the patch applied earlier so that we are once again using remote state
- initialize the remote backend: `make prep`
- push fixed state to remote: `terraform state push /local/state/copy/path`

## Apply to remote state

- `make apply`
- verify by log inspection that deployment `custom-metrics/custom-metrics-adapter` is healthy and can read the SQS queue depth metrics
